name = "sharemytodo"
main = "src/index.ts"
compatibility_date = "2022-07-05"
node_compat = true

kv_namespaces = [
    { binding = "SHAREMYTODO_KV", id = "c6cd82931753427598dd4568521ec198" }
]

[env.dev]
vars = { JWT_SECRET = "test", MAC_KEY = "test" }
kv_namespaces = [
    { binding = "SHAREMYTODO_KV", id = "d5d9096c472540f78fb9cdb2727aad23" }
]
